doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '10.4'
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        mappings:
            App:
                is_bundle: false
                type: annotation   # Utilisation des annotations comme type de mapping
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
