framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true

    # Configuring the annotation reader
    annotations:
        enabled: true

    # Default configuration for "framework" extension.
    # https://symfony.com/doc/current/reference/configuration/framework.html
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    # Configuring the serializer
    serializer: { enable_annotations: true }

    # Configuring the cache
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'

        pools:
            my_custom_cache:
                default_lifetime: 3600
            my_other_cache:
                default_lifetime: 1800
