twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
