# config/services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Migrations,Tests,Kernel.php}'

    # Inclure explicitement l'entité Cellier pour permettre l'autowiring
    App\Entity\Cellier:
        autowire: true

    # Exemples de contrôleurs spécifiques avec des arguments définis
    App\Controller\RegistrationController:
        autowire: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $passwordHasher: '@security.password_hasher'

    App\Controller\ListeController:
        autowire: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    # Tag pour indiquer que les arguments du contrôleur doivent être résolus automatiquement
    App\Controller\BouteilleController:
        tags: ['controller.service_arguments']

    # Ajout du service pour BouteilleCellierController avec arguments
    App\Controller\BouteilleCellierController:
        autowire: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['controller.service_arguments']
